  web:
    build: .
    command: python app/manage.py
    ports:
     - "5000:5000"
    volumes:
     - .:/app
    links:
     - mysql
    hostname: myappserver
  mysql:
    image: mysql:latest
    volumes:
     - /var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=123456
     - MYSQL_DATABASE=geodata
    ports:
     - 3306:3306