  web:
    build: .
    command: python code/untitled.py
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    links:
     - db
    hostname: myappserver
  db:
    hostname: mysqlserver
    image: orchardup/mysql
    environment:
       MYSQL_ROOT_PASSWORD: p@ssw0rd123
       MYSQL_DATABASE: wordpress